
spring:
  application:
    name: SIWA_Project
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb2
    username: sa
    password: 111
    #    localhost/8082/h2-console
  jpa:
    defer-datasource-initialization: true # 테이블 생성 순서 schema > data > entity
#    #    권한
    generate-ddl: true
    show-sql: true
    hibernate:
#      #   create: 테이블을 삭제하고 생성함 > 외래키를 참조 하고 있는지 확인
      ddl-auto: create # create create-drop update validate
    properties:
      hibernate:
#        # 예약어를 사용할 때 "" 감싸서 문자열로 바꾸는 설정
#        auto_quote_keyword: true
#        #        spring 콘솔에 출력되는 sql을 보기 좋게 형식을 바꿈
        format_sql: true
#  # data.sql 적용
##  sql:
##    init:
##      mode: always
#
#
server:
  port: 8081
#logging:
#  level:
#    sql: trace
##    root: trace
##    web: trace
